<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @since         DebugKit 5.1
 * @license       https://www.opensource.org/licenses/mit-license.php MIT License
 */
namespace DebugKit;

use Cake\Core\Configure;

/**
 * Contains methods for dumping well formatted SQL queries.
 */
class DebugStatements
{
    /**
     * @var array<string>
     */
    protected static $statements = [];

    /**
     * @return array<string>
     */
    public static function all(): array
    {
        return static::$statements;
    }

    /**
     * Template used for HTML output.
     *
     * @var string
     */
    private static string $templateHtml = <<<HTML
<div class="cake-debug-output">
%s
<pre class="cake-debug">
%s
</pre>
</div>
HTML;

    /**
     * Template used for CLI and text output.
     *
     * @var string
     */
    private static string $templateText = <<<TEXT
%s
########## DEBUG ##########
%s
###########################

TEXT;

    /**
     * Prints out the SQL statements generated by a Query object.
     *
     * This function returns the same variable that was passed.
     * Only runs if debug mode is enabled.
     *
     * @param mixed $var
     * @param bool|null $showHtml
     * @param array $location
     * @return string Empty string.
     */
    public static function add(mixed $var, ?bool $showHtml = null, array $location = []): string
    {
        if (!Configure::read('debug')) {
            return '';
        }

        static::$statements[] = [
            'var' => $var,
            'showHtml' => $showHtml,
            'location' => $location,
        ];

        return '';
    }
}
